=== Dzemitelolkek/Medlifeprk/src/assets/config.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "id": "http://link.to.gitlab",
  "title": "TehLab Onco Alertness config schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "BECKEND_CONTEXT": {
      "type": "string"
    },
    "FIELD_CODE_RESULT": {
      "type": "string"
    },
    "LOGO_IMG": {
      "type": "string"
    },
    "TITLE_TEXT": {
      "type": "string"
    },
    "ORGANIZATION_TEXT": {
      "type": "string"
    },
    "PHONES": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ADDRESS": {
      "type": "string"
    },
    "EMAIL": {
      "type": "string"
    }
  },
  "required": [
    "BECKEND_CONTEXT",
    "FIELD_CODE_RESULT",
    "LOGO_IMG",
    "TITLE_TEXT"
  ],
  "additionalProperties": false
}

=== Dzemitelolkek/Medlifeprk/src/assets/config.json
{
  "$schema": "./config.schema.json",
  "BECKEND_CONTEXT": "https://develop-oncoalertness.dev.teh-lab.ru",
  "FIELD_CODE_RESULT": "someField",
  "LOGO_IMG": "logotip2.jpg",
  "TITLE_TEXT": "ООО \"МЕДЛАЙФ\"",
  "ORGANIZATION_TEXT": "медицинский  центр",
  "PHONES": ["8(3846) 652-652", "8-903-0-677-888"],
  "ADDRESS": "Кемеровская обл. г. Прокопьевск ул. Гайдара, дом 50а Офис 303",
  "EMAIL": "medlife.prk@mail.ru"
}
